"""
ui.glossary
===========

Glossary user interface components.

Responsibilities
----------------
* Provide glossary-related UI components.
* Present glossary browsing/help functionality.
* Provide a location for future glossary interaction controls.

This module is separate from:

    ingestion/glossary.py

which performs ingestion-time exact matching and creates the
paragraph_terms index.

The UI does NOT calculate glossary matches.

Glossary hyperlinks inside paragraphs are generated by:

    renderer.renderer

and are rendered by:

    ui.cards

This module only provides user-facing glossary controls.
"""

from __future__ import annotations

from shiny import ui

###############################################################################
# IDs
###############################################################################

GLOSSARY_PANEL_ID = "glossary_panel"
GLOSSARY_SEARCH_ID = "glossary_search"

###############################################################################
# Public API
###############################################################################


def build_glossary_panel():
    """
    Build the glossary interface.

    The initial implementation provides a compact glossary
    information panel. Future versions may connect this panel
    to a searchable glossary browser backed by the database.

    Returns
    -------
    shiny.ui.Tag
        Glossary UI component.
    """

    return ui.div(
        ui.h3(
            "Glossary",
            class_="section-title",
        ),

        ui.p(
            (
                "Glossary terms appearing in search results are "
                "shown as clickable links. Selecting a term "
                "runs a search for that term."
            ),
            class_="section-description",
        ),

        ui.input_selectize(
            id=GLOSSARY_SEARCH_ID,
            label="Browse glossary terms",
            choices=[],
            multiple=False,
            width="100%",
        )

        ui.div(
            ui.output_ui(
                GLOSSARY_PANEL_ID
            ),
            class_="glossary-results",
        ),

        class_="glossary-panel",
    )


###############################################################################
# Server helpers
###############################################################################


def register_glossary_renderer(
    *,
    output,
    terms_provider=None,
):
    """
    Register the glossary browse output.

    Parameters
    ----------
    output
        Shiny output object.

    terms_provider
        Optional callable returning glossary terms.

        This is intentionally injected rather than imported from
        the database layer. It keeps this module independent from
        storage implementation.

    Notes
    -----
    The current application workflow does not require glossary
    searching because glossary matches are already stored during
    ingestion.

    This hook exists for a future glossary browsing feature.
    """

    if terms_provider is None:

        @output(GLOSSARY_PANEL_ID)
        def glossary_panel():
            return ui.p(
                (
                    "Glossary browsing will be available "
                    "in a future release."
                )
            )

        return

    @output(GLOSSARY_PANEL_ID)
    def glossary_panel():
        terms = terms_provider()

        if not terms:
            return ui.p(
                "No glossary terms available."
            )

        return ui.div(
            *[
                ui.span(
                    term,
                    class_="glossary-term",
                )
                for term in terms
            ],
            class_="glossary-term-list",
        )