"""
Semantic embedding generation and similarity-based topic tagging.

This module implements the second layer of the topic-tagging pipeline.

Pipeline
--------
1. Load the BAAI/bge-base-en-v1.5 sentence embedding model.
2. Generate embeddings for configured topic anchors.
3. Generate embeddings for paragraphs.
4. Compute cosine similarity.
5. Produce candidate topic tags above a configurable threshold.

The embedding layer is deterministic and performs no database writes.
Persistence is handled by tagging.pipeline.

Paragraph embeddings are returned so they can be stored and reused by
future semantic search implementations (e.g. Elasticsearch or pgvector).

Model
-----
BAAI/bge-base-en-v1.5

Reference
---------
https://huggingface.co/BAAI/bge-base-en-v1.5
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from functools import cached_property
from typing import Iterable
from typing import Mapping
from typing import Sequence

import numpy as np
from sentence_transformers import SentenceTransformer

from core.config import settings
from tagging.anchors import TopicAnchor
from tagging.anchors import load_anchor_dictionary

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------


@dataclass(slots=True, frozen=True)
class ParagraphEmbedding:
    """
    Embedding generated for a paragraph.

    Attributes
    ----------
    vector

        L2-normalised embedding.

    model

        HuggingFace model identifier.

    dimension

        Embedding dimensionality.
    """

    vector: np.ndarray
    model: str
    dimension: int


@dataclass(slots=True, frozen=True)
class SimilarityMatch:
    """
    Candidate topic generated by cosine similarity.
    """

    topic: str
    similarity: float
    confidence: float
    matched_phrase: str
    layer: str = "embedding"


# ---------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------


def l2_normalize(vector: np.ndarray) -> np.ndarray:
    """
    L2-normalise an embedding.

    Parameters
    ----------
    vector

        Raw embedding.

    Returns
    -------
    numpy.ndarray
    """

    norm = np.linalg.norm(vector)

    if norm == 0.0:
        return vector

    return vector / norm


def cosine_similarity(
    left: np.ndarray,
    right: np.ndarray,
) -> float:
    """
    Cosine similarity between two normalised vectors.

    Parameters
    ----------
    left

        First embedding.

    right

        Second embedding.
    """

    return float(np.dot(left, right))


# ---------------------------------------------------------------------
# Embedding model
# ---------------------------------------------------------------------


class EmbeddingModel:
    """
    Thin wrapper around SentenceTransformer.

    The model is loaded lazily.

    A single instance should be shared throughout the application.
    """

    def __init__(
        self,
        model_name: str | None = None,
        device: str | None = None,
    ) -> None:

        self._model_name = (
            model_name
            or settings.embedding_model
        )

        self._device = (
            device
            or settings.embedding_device
        )

    @cached_property
    def model(self) -> SentenceTransformer:
        """
        Lazily load the transformer model.
        """

        logger.info(
            "Loading embedding model '%s' on device '%s'.",
            self._model_name,
            self._device,
        )

        return SentenceTransformer(
            self._model_name,
            device=self._device,
        )

    @property
    def model_name(self) -> str:
        return self._model_name

    # --------------------------------------------------------------

    def embed(
        self,
        text: str,
    ) -> ParagraphEmbedding:
        """
        Generate an embedding for a single paragraph.
        """

        vector = self.model.encode(
            text,
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=False,
        )

        vector = l2_normalize(vector)

        return ParagraphEmbedding(
            vector=vector,
            model=self._model_name,
            dimension=int(vector.shape[0]),
        )

    # --------------------------------------------------------------

    def embed_many(
        self,
        texts: Sequence[str],
        *,
        batch_size: int | None = None,
    ) -> list[ParagraphEmbedding]:
        """
        Batch embedding generation.
        """

        if not texts:
            return []

        batch_size = (
            batch_size
            or settings.embedding_batch_size
        )

        vectors = self.model.encode(
            texts,
            batch_size=batch_size,
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=False,
        )

        embeddings: list[ParagraphEmbedding] = []

        for vector in vectors:

            vector = l2_normalize(vector)

            embeddings.append(
                ParagraphEmbedding(
                    vector=vector,
                    model=self._model_name,
                    dimension=int(vector.shape[0]),
                )
            )

        return embeddings


# ---------------------------------------------------------------------
# Anchor embedding cache
# ---------------------------------------------------------------------


class AnchorEmbeddingStore:
    """
    Cache of topic anchor embeddings.

    Anchor embeddings are computed once and reused for every paragraph.
    """

    def __init__(
        self,
        embedding_model: EmbeddingModel,
        anchors: Sequence[TopicAnchor] | None = None,
    ) -> None:

        self._embedding_model = embedding_model

        self._anchors = tuple(
            anchors
            if anchors is not None
            else load_anchor_dictionary()
        )

    @cached_property
    def embeddings(
        self,
    ) -> Mapping[str, list[tuple[str, np.ndarray]]]:
        """
        Returns
        -------
        dict

            topic ->
                [
                    (anchor phrase, embedding),
                    ...
                ]
        """

        logger.info(
            "Embedding %d configured topic anchors.",
            len(self._anchors),
        )

        cache: dict[str, list[tuple[str, np.ndarray]]] = {}

        for topic in self._anchors:

            phrase_embeddings: list[
                tuple[str, np.ndarray]
            ] = []

            for phrase in topic.phrases:

                embedding = self._embedding_model.embed(
                    phrase
                )

                phrase_embeddings.append(
                    (
                        phrase,
                        embedding.vector,
                    )
                )

            cache[topic.name] = phrase_embeddings

        return cache


# ---------------------------------------------------------------------
# Similarity layer
# ---------------------------------------------------------------------


class SimilarityTagger:
    """
    Generates candidate topic tags using cosine similarity
    against embedded topic anchors.

    Only tags exceeding the configured similarity threshold
    are returned.

    The highest-scoring anchor phrase for each topic is retained.
    """

    def __init__(
        self,
        embedding_model: EmbeddingModel | None = None,
        anchor_store: AnchorEmbeddingStore | None = None,
        *,
        similarity_threshold: float | None = None,
    ) -> None:

        self._embedding_model = (
            embedding_model
            or EmbeddingModel()
        )

        self._anchor_store = (
            anchor_store
            or AnchorEmbeddingStore(
                self._embedding_model,
            )
        )

        self._threshold = (
            similarity_threshold
            if similarity_threshold is not None
            else settings.embedding_similarity_threshold
        )

    # --------------------------------------------------------------

    def tag(
        self,
        paragraph: str,
    ) -> tuple[
        ParagraphEmbedding,
        list[SimilarityMatch],
    ]:
        """
        Generate semantic topic candidates for a paragraph.

        Returns
        -------
        tuple

            ParagraphEmbedding

            list[SimilarityMatch]
        """

        paragraph_embedding = self._embedding_model.embed(
            paragraph,
        )

        matches: list[SimilarityMatch] = []

        for topic, phrase_embeddings in (
            self._anchor_store.embeddings.items()
        ):

            best_score = -1.0
            best_phrase = ""

            for phrase, anchor_vector in phrase_embeddings:

                score = cosine_similarity(
                    paragraph_embedding.vector,
                    anchor_vector,
                )

                if score > best_score:
                    best_score = score
                    best_phrase = phrase

            if best_score < self._threshold:
                continue

            matches.append(
                SimilarityMatch(
                    topic=topic,
                    similarity=best_score,
                    confidence=best_score,
                    matched_phrase=best_phrase,
                )
            )

        matches.sort(
            key=lambda match: match.similarity,
            reverse=True,
        )

        logger.debug(
            "Embedding layer produced %d semantic candidates.",
            len(matches),
        )

        return paragraph_embedding, matches

    # --------------------------------------------------------------

    def tag_many(
        self,
        paragraphs: Iterable[str],
    ) -> dict[int, tuple[ParagraphEmbedding, list[SimilarityMatch]]]:
        """
        Apply semantic tagging to multiple paragraphs.
        """

        results: dict[
            int,
            tuple[
                ParagraphEmbedding,
                list[SimilarityMatch],
            ],
        ] = {}

        for index, paragraph in enumerate(paragraphs):

            results[index] = self.tag(paragraph)

        return results


# ---------------------------------------------------------------------
# Confidence utilities
# ---------------------------------------------------------------------


def is_high_confidence(
    similarity: float,
    *,
    threshold: float | None = None,
) -> bool:
    """
    Determine whether a similarity score should be accepted without
    LLM verification.

    Parameters
    ----------
    similarity
        Cosine similarity score.

    threshold
        Optional override of the configured threshold.

    Returns
    -------
    bool
    """

    limit = (
        threshold
        if threshold is not None
        else settings.embedding_similarity_threshold
    )

    return similarity >= limit


def requires_llm_verification(
    similarity: float,
) -> bool:
    """
    Determine whether a similarity score falls within the configurable
    low-confidence band that should be sent to the verifier.

    Notes
    -----
    Scores below the lower bound are rejected immediately.
    Scores above the upper bound are accepted immediately.
    Scores inside the band are deferred to the LLM verifier.
    """

    return (
        settings.embedding_low_confidence_min
        <= similarity
        < settings.embedding_low_confidence_max
    )


# ---------------------------------------------------------------------
# Convenience API
# ---------------------------------------------------------------------


_default_model: EmbeddingModel | None = None
_default_store: AnchorEmbeddingStore | None = None
_default_tagger: SimilarityTagger | None = None


def get_embedding_model() -> EmbeddingModel:
    """
    Return the process-wide embedding model singleton.
    """

    global _default_model

    if _default_model is None:
        _default_model = EmbeddingModel()

    return _default_model


def get_anchor_store() -> AnchorEmbeddingStore:
    """
    Return the cached anchor embedding store.
    """

    global _default_store

    if _default_store is None:
        _default_store = AnchorEmbeddingStore(
            get_embedding_model(),
        )

    return _default_store


def get_similarity_tagger() -> SimilarityTagger:
    """
    Return the default semantic tagger.
    """

    global _default_tagger

    if _default_tagger is None:
        _default_tagger = SimilarityTagger(
            embedding_model=get_embedding_model(),
            anchor_store=get_anchor_store(),
        )

    return _default_tagger


def embed_paragraph(
    paragraph: str,
) -> ParagraphEmbedding:
    """
    Convenience wrapper for embedding a single paragraph.
    """

    return get_embedding_model().embed(paragraph)


def embed_paragraphs(
    paragraphs: Sequence[str],
) -> list[ParagraphEmbedding]:
    """
    Convenience wrapper for batch embedding.
    """

    return get_embedding_model().embed_many(paragraphs)


def tag_paragraph(
    paragraph: str,
) -> tuple[
    ParagraphEmbedding,
    list[SimilarityMatch],
]:
    """
    Generate semantic topic candidates for a single paragraph.
    """

    return get_similarity_tagger().tag(paragraph)


def tag_paragraphs(
    paragraphs: Iterable[str],
) -> dict[
    int,
    tuple[
        ParagraphEmbedding,
        list[SimilarityMatch],
    ],
]:
    """
    Generate semantic topic candidates for multiple paragraphs.
    """

    return get_similarity_tagger().tag_many(paragraphs)


# ---------------------------------------------------------------------
# Public exports
# ---------------------------------------------------------------------

__all__ = [
    "AnchorEmbeddingStore",
    "EmbeddingModel",
    "ParagraphEmbedding",
    "SimilarityMatch",
    "SimilarityTagger",
    "cosine_similarity",
    "embed_paragraph",
    "embed_paragraphs",
    "get_anchor_store",
    "get_embedding_model",
    "get_similarity_tagger",
    "is_high_confidence",
    "l2_normalize",
    "requires_llm_verification",
    "tag_paragraph",
    "tag_paragraphs",
]